# Generated by Django 5.1 on 2024-08-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContainerPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=255)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="containers__name_b20f0c_idx"),
                    models.Index(
                        fields=["name", "version"], name="containers__name_d1518a_idx"
                    ),
                    models.Index(
                        fields=["name", "version", "provider"],
                        name="containers__name_88b0ea_idx",
                    ),
                ],
                "unique_together": {("name", "version", "provider")},
            },
        ),
        migrations.CreateModel(
            name="ContainerTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=255)),
                ("fullname", models.CharField(max_length=255)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tag"], name="containers__tag_38cbb6_idx"),
                    models.Index(
                        fields=["fullname"], name="containers__fullnam_8120c5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContainerBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cid", models.CharField(max_length=255)),
                ("cname", models.CharField(max_length=255)),
                ("osname", models.CharField(max_length=255, null=True)),
                ("osversionid", models.CharField(max_length=255, null=True)),
                ("time", models.DateTimeField()),
                ("ctime", models.DateTimeField()),
                ("packages", models.ManyToManyField(to="containers.containerpackage")),
                ("tags", models.ManyToManyField(to="containers.containertags")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["cid"], name="containers__cid_e5717f_idx"),
                    models.Index(
                        fields=["osname", "osversionid"],
                        name="containers__osname_95531a_idx",
                    ),
                ],
            },
        ),
    ]
