# Generated by Django 6.0.5 on 2026-06-04 06:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Who/what this key is for.", max_length=100
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        default=api.models.generate_key,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
