# Generated by Django 5.1.4 on 2024-12-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0002_containerimage_servers_con_image_108589_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hostdetails",
            options={"ordering": ("-time",)},
        ),
    ]
