# Generated by Django 5.1.4 on 2025-04-14 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0003_alter_hostdetails_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ctype", models.CharField(max_length=255)),
                ("name", models.CharField()),
                ("value", models.CharField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ctype", "name"], name="servers_con_ctype_700a43_idx"
                    ),
                    models.Index(
                        fields=["ctype", "name", "value"],
                        name="servers_con_ctype_ff970e_idx",
                    ),
                ],
                "unique_together": {("ctype", "name", "value")},
            },
        ),
        migrations.CreateModel(
            name="HostConfigs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("configs", models.ManyToManyField(to="servers.configvalues")),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="servers.host"
                    ),
                ),
            ],
        ),
    ]
